autoload/previm.vim

fix #27 add option of disable vimproc

---

.travis.yml
test/autoload/previm_test.vim
test/plugin/previm_test.vim

#35 switch vimtest to themis

---

autoload/previm.vim
test/autoload/previm_test.vim

[#32] support image with title

---

autoload/previm.vim

ref #46 support latest open-browser.vim

---

autoload/previm.vim

Windows でブラウザが開かなくなった(いつからか)のでパスをノーマライズする様にしました。

Normalize path on windows

---

autoload/previm.vim

windows環境のfirefoxで動くようにprevim.vimを修正しました。
17行目あたりです。
よろしくお願いします。

fix #45, open on firefox by windows environment.

---

preview/index.html

The content is not necessarily in Japanese.

Removed lang="ja"

---

doc/previm.jax
doc/previm.txt

I think better doc has chome setting's illustration. :-)

open chrome

---

README-en.mkd
README.mkd
doc/previm.jax
doc/previm.txt

* Vim [v7.4.480](https://github.com/vim/vim/commit/7d76c804af900ba6dcc4b1e45373ccab3418c6b2#diff-44a099e40ae628aef90a28c6408a4c6://github.com/vim/vim/commit/7d76c804af900ba6dcc4b1e45373ccab3418c6b2#diff-44a099e40ae628aef90a28c6408a4c61) 以降不要になっている記述を削除
* READMEの連番の記述を統一

refs #117 Update markdown description

---

README-en.mkd
README.mkd

mermaid へのリンク先が 404 だったのを更新しました。

Update link to mermaid page

---

autoload/previm.vim

Escape carriage return

---

autoload/previm.vim
doc/previm.jax
doc/previm.txt
preview/_/js/lib/plantuml.js

Add g:previm_plantuml_imageprefix

---

README-en.mkd
README.mkd

Add documentation about PlantUML

---

.travis.yml

I have added various Vim versions to unit tests.
- Vim7.4
- Vim8
- Vim8.1
- Vim8.2

[add] some vim's version test

---

autoload/previm.vim

Fix multiple images in the same line

---

README-en.mkd
doc/previm.txt

I found my cache very full recently and found these commands that were not yet documented. If there's anyone that can suggest the Japanese translations I can add those too.

Document commands PrevimRefresh and PrevimWipeCache (English only)

---

autoload/previm.vim

feat: add g:previm_custom_preview_base_dir

---

preview/_/css/origin.css

Checkbox `[ ]` `[x]` right space is too small.

Modify checkbox spacing

---

doc/previm.txt

Fix a typo in the English document.

Fix a typo

---

preview/_/index.html.tmpl
preview/_/js/previm.js.tmpl

This may fix #178.
* cf. https://izm51.com/posts/markdown-it-target-blank-anchor/
* cf. https://sunday-morning.app/posts/2019-06-28-markdown-it

Open anchor link in the current page into the current window

---

autoload/previm/assets.vim

Fix markdown-it source path

---

autoload/previm.vim

Fix in-page anchor link target has come to be wrong in local file link support

---

autoload/previm.vim

Fix #207. It may fix #206 as well?

Escape text prior to convert path

---

autoload/previm.vim

Fix for #206 and #207, footnote issues (cf. https://github.com/previm/previm/issues/206#issuecomment-2510656288).

Fix footnote issues

---

autoload/previm.vim
test/autoload/previm_test.vim

feat: import default css into layers
