autoload/previm.vim

1つの行に画像のパスのみでない場合(例えば画像を含む表)に対応しました。具体的には以下のMarkdownソースで正しく変換できるようにしました。
```
| name | image |
| - | ---- |
| a | ![image1](1.png) |
| b | ![image2](2.png) |
| c | ![image3](3.png) |
```
ただし、1つの行に複数の画像のパスを含む場合には対応していません。

fix replacing imgpath

---

preview/js/previm.js

いつも便利にprevimを使わせていただいております。
コードブロック部分の表示についてなのですが、ブロック内の`<`や`>`といった文字がエスケープされていませんでした。なので例えば以下のようなコードブロックを書くと、`<C-u>`や`<Space>`が通常のHTMLタグとして解釈されてしまい、画面に表示されません。
(`\`はgithubにmarkdownと解釈されないよう便宜的につけています)
```
\```
nnoremap <C-h> :<C-u>help<Space>
\```
```
ブラウザ上の表示:
```
nnoremap :help
```
#38 の修正で`mermaid`をサポートした際、`marked.Renderer.code`関数をオーバーライドした事でエスケープされなくなってしまったようです。デフォルトの`code`関数はエスケープもしてくれるので、`mermaid`でないコードブロックにはそのままデフォルトの`code`関数を使うよう修正しました。

Escape html-tags in code block

---

autoload/previm.vim
test/autoload/previm_test.vim

previmはMarkdownテキストをHTMLに変換する前に、相対パスのイメージがある場合はそのパスを絶対パスに置き換えていますが、イメージが別のリンクの中に埋め込まれているとこの処理が上手くいっていないようです。具体的には以下のような記述です。どちらもイメージに他のファイルへのリンクを貼っています。
1. `[![img-alt](img/path)](/path/to/another/file)`
2. `[![img-alt][img-path]](/path/to/another/file)`
現状使用されている正規表現で上記のような記述からイメージのパスを取得しようとすると、余計な部分までマッチしてしまい、パスが正しく変換されません。
Expected:
1. `{'alt': 'img-alt', 'path': 'img/path'}`
2. `{'alt': '', 'path': ''}`
Actual:
1. `{'alt': 'img-alt](img/path)', 'path': '/path/to/another/file'}`
2. `{'alt': 'img-alt][img-path]', 'path': '/path/to/another/file'} `
そのため、`[`から`]`、及び`(`から`)`までの最も短い文字列にマッチするように正規表現を修正しました。

Get image path inside of link correctly

---

preview/css/lib/mermaid.css

mermaid.cssでsectionに指定しているCSSの影響で、
CSS指定したdivタグの内容がほぼ見えなくなっているのでopacityの設定を削除しました。
#43 の件もこれが影響していたと思われます。
ご確認よろしくお願いします。

Remove opacity of .section because it cannot see in rst file.

---

autoload/previm.vim

mkd_dir should be path-slash-ed always on Windows. backslash are replaced double. ex: `\` to `\\`, and it will be `%5c`. To avoid this problem, replace backslashs to slash in mkd_dir always on Windows.

fix image paths on Windows

---

preview/css/origin.css

Changes the `width` property to a `max-width` property so that small
images aren't blown up, while large images are scaled down.  
Referencing #82 and #65.

Fix bloated issues #82 while conforming to #65

---

autoload/previm.vim

On Windows, executable("rst2html.py") return 1 even though if .py is not
registered to python.exe. So rst2html should be handled before
rst2html.py.

prefer rst2html than rst2html.py on Windows

---

autoload/previm.vim

Added parentheses to the condition to judge as win & firefox.
Under the condition before modification, if I set chrome command in windows, previm judge as win & firefox. As a result, previm was trying to open an incorrect file path with chrome and got into file not found error.

Fix the condition to judge as win & firefox environment.

---

.gitignore

When cloning previm into the vim plugins dir it will show as dirty as previews accumulate in the preview dir. This .gitignore change will ignore them but still include the "_" dir which appears to have useful files in it. Note the "_" was ignored previously in .gitignore which I have reversed, I assume this was a mistake.

Ignore changes in the preview dir (apart from _)

---

autoload/previm.vim

Windows Subsystem for Linux(WSL)に対応するためのモードです。
`.vimrc` にて、`let g:previm_wsl_mode = 1` と指定することで、WSL上のLinuxから `g:previm_open_cmd` で指定したブラウザで開くことができます。
```vim:example
let g:previm_open_cmd = '/mnt/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe'
let g:previm_wsl_mode = 1
```
WSL上で実行される `a:preview_html_file` は、Linuxと同様に `/home/hirano00o/.vim/.../index.html` となり、Windowsから見えるパスとは異なります。
WSL <-> Windows のパス変換をするために、`wslpath` を利用します。
`wslpath` は、WSL では標準で利用できます。
この `wslpath` を利用し、`g:previm_wsl_mode = 1` のときは、
`wslpath -w a:preview_html_file`
を実行し、
`/home/hirano00o/.vim.../index.html` -> `\\wsl$\Ubuntu\home\hirano00o/.vim/.../index.html`
と変換してWindowsのブラウザへ渡すことで、表示することが可能です。
`g:previm_wsl_mode` が、`1` 以外、または.vimrcで指定されていない場合は、elseifをスルーします。

add previm_wsl_mode

---

autoload/previm.vim

https://github.com/previm/previm/pull/135 で追加された`previm_wsl_mode`をfish shellから使用した場合に、`:PrevimOpen`をしてもpreviewをブラウザで開くことができなかったため修正しました。
* Windows 10
* WSL
* fish: version 3.0.2-1910-g9efb7fd5
シェルで`{ブラウザの実行ファイルへのパス} '{ファイルパス}'`を実行した場合に、shやbashとfishではファイルパスの解釈の仕方が違うようです。
そのためfishから実行するとpreview用のファイルにアクセスできなくなっていました。
ex)
**bash × Chrome**
```
$ /mnt/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe '\\wsl$\Ubuntu\home\ryotatake\test.md'
=> file://wsl%24/Ubuntu/home/ryotatake/test.md がブラウザで開かれる。
```
**fish × Chrome**
```
$ /mnt/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe '\\wsl$\Ubuntu\home\ryotatake\test.md'
=> http://www.wsl%24/Ubuntu/home/ryotatake/test.md がブラウザで開かれる。
```
**bash × Firefox**
```
$ /mnt/c/Program\ Files/Mozilla\ Firefox/firefox.exe …
```

fix previm_wsl_mode for fish shell

---

plugin/previm.vim

Making `previm#refresh()` as a user command is something bad?
In case realtime preview is off (`g:previm_enable_realtime = 0`),
writing the file, or calling `PrevimOpen` newly is only the way to update the preview now.

Add `PrevimRefresh` command

---

plugin/previm.vim
preview/_/js/previm.js

Fix for #165: support `mermaid` or `mmd` file type.
Just add Markdown code fence ` ```mermaid ... ``` ` to whole file content, and render as a Markdown file.

[Feature] Support Mermaid.js file (`*.mmd`)

---

autoload/previm.vim

Thanks for a useful plugin.
This PR fix the path to image in markdown when `let g:previm_wsl_mode = 1`.
WSL was treated as Unix, and the following path was generated.
`![alt](file://localhost/home/halkn/Pictures/img.png "title")`
But in WSL, paths like above cannot be opened from Windows browser.
Use wslpath to convert to a path that can be referenced from Windows browser.
`![alt](\\wsl$\Ubuntu\home\halkn\Pictures\img.png "title")`

Fix imgpath in wsl_mode.

---

preview/_/index.html

Current link target is the preview page itself (i.e. `target="_self"`).
However, going back from a link page, it takes a while to reload the preview.
Instead, shouldn't it open links in new tabs?

Set default link target `_blank`

---

autoload/previm.vim

Suggested partial fix for #159 - do not generate/refresh a preview unless user has asked to see it at least once (i.e. opened the browser). This will cut down on number of files in the preview cache considerably.

Skip refresh if browser has not been opened on a buffer

---

autoload/previm.vim

Fix for https://github.com/previm/previm/issues/174.
Along with it, re-enabled buffer-wise setting `b:previm_hard_line_break`.
If you think it should not be, revert the latter commit 008f5f7.

[Bugfix] Hard-line-break option (`g:previm_hard_line_break`)

---

README.md

The link to the english README file is broken since the rename from  'README.mkd'

fix: broken link to README-en.md (after change from '.mkd')

---

doc/previm.jax
doc/previm.txt

Add an option description was not included in the documentation.(g:previm_hard_line_break)

Add an option description was not included in the documentation.

---

autoload/previm.vim
test/autoload/previm_test.vim

Support local link along with local image reference.
Now it only supports local image (e.g. `![ALT_TEXT](local/image/path.png)`).
Along with this, make it support local link (e.g. `[LINK_TEXT](local/file/path.txt)`, the syntax not `!`-preceding).
Also, handle local link label (e.g. `[LABEL]: local/file/path.txt`).
This syntax is used for both of link (`[LINK_TEXT][LABEL]`) and image (`![ALT_TEXT][LABEL]`).
Constraints:
Of course, local link for markdown is opened as raw text without rich-styling.

Handle Local Link

---

autoload/previm.vim
doc/previm.jax
doc/previm.txt
preview/_/css/origin.css
preview/_/js/previm.js.tmpl

Added highlighting of the following code blocks.
- Normal code blocks
````markdown
```ruby
puts 'The best way to log and share programmers knowledge.'
```
````
- Qiita, Zenn style (Separetor by a coron)
````markdown
```ruby:qiita.rb
puts 'The best way to log and share programmers knowledge.'
```
````
- VSCode, Vim style (Separetor by a space)
````markdown
```apache /etc/apache/conf.d/conf/foo.conf
ServerTokens Major
Listen 80
```
````
- [Markdown記法 チートシート - Qiita](https://qiita.com/Qiita/items/c686397e4a0f4f11683d#code---%E3%82%B3%E3%83%BC%E3%83%89%E3%81%AE%E6%8C%BF%E5%85%A5)
- [ZennのMarkdown記法一覧](https://zenn.dev/zenn/articles/markdown-guide#%E3%82%B3%E3%83%BC%E3%83%89%E3%83%96%E3%83%AD%E3%83%83%E3%82%AF)

Support for language display of code blocks

---

autoload/previm.vim

Reverts previm/previm#208
This commit caused #212 and test failure.

Revert "Escape text prior to convert path"
